
const productos = [
    {id:1,
      nombre:"Preastamos Dia del Padre", 
      img:"./imagenes/diaDelPadre.jpg",
      prestamo:18000, 
      cuotas:1500},
    {id:2,
      nombre:"Prestamos Mis Quince",
      img:"./imagenes/misQuince.jpg",
      prestamo:70000, 
      cuotas: 2500},
    {id:3, 
      nombre:"Prestamos para Estudiantes",
      img:"./imagenes/prestamoEstudiante.jpg",
      prestamo:30000,
      cuotas:1000},
    {id:4,
      nombre:"Prestamos se agrando la familia",
      img:"./imagenes/cunaBebe.jpg", 
      prestamo:45000,
      cuotas:2000},
    {id:5,
      nombre:"Prestamos vacaciones",
      img:"./imagenes/vacaciones.jpg",
      prestamo:50000, 
      cuotas:2500},
    {id:6,
      nombre:"Prestamos Empleado Publico", 
      img:"./imagenes/empleadoPublico.jpg",
      prestamo:35000,
      cuotas:1500},
    {id:7, 
      nombre:"Prestamos Jubilados",
      img:"./imagenes/jubilados.jpg",
      prestamo:30000, 
      cuotas:1000},
    {id:8, 
      nombre:"Prestamos Adelanto Aguinaldo", 
      img:"./imagenes/aguinaldo.jpg",
      prestamo:25000, 
      cuotas:500}
];

guardarPrestamosLS();